Site/src/Sistema.TSTOnline.Web/Models/Produtos/CategoriaVM.cs
using Newtonsoft.Json;

namespace Sistema.TSTOnline.Web.Models.Produtos
{
    public class CategoriaVM
    {
        [JsonProperty(PropertyName = "codigo")]
        public int IDCategoria { get; set; }

        [JsonProperty(PropertyName = "descricao")]
        public string Descricao { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Models/Produtos/ProdutoVM.cs
using Newtonsoft.Json;

namespace Sistema.TSTOnline.Web.Models.Produtos
{
    public class ProdutoVM
    {
        [JsonProperty(PropertyName = "idProduto")]
        public int IDProduto { get; set; }

        [JsonProperty(PropertyName = "sku")]
        public string SKU { get; set; }

        [JsonProperty(PropertyName = "nome")]
        public string Nome { get; set; }

        [JsonProperty(PropertyName = "descricao")]
        public string Descricao { get; set; }

        [JsonProperty(PropertyName = "idFornecedor")]
        public int IDFornecedor { get; set; }

        [JsonProperty(PropertyName = "fornecedorRazaoSocial")]
        public string FornecedorRazaoSocial { get; set; }

        [JsonProperty(PropertyName = "idCategoria")]
        public int IDCategoria { get; set; }

        [JsonProperty(PropertyName = "categoriaDescricao")]
        public string CategoriaDescricao { get; set; }

        [JsonProperty(PropertyName = "idSubCategoria")]
        public int IDSubCategoria { get; set; }

        [JsonProperty(PropertyName = "subCategoriaDescricao")]
        public string SubCategoriaDescricao { get; set; }

        [JsonProperty(PropertyName = "preco")]
        public decimal Preco { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Models/Produtos/SubCategoriaVM.cs
using Newtonsoft.Json;

namespace Sistema.TSTOnline.Web.Models.Produtos
{
    public class SubCategoriaVM
    {
        [JsonProperty(PropertyName = "codigo")]
        public int IDSubCategoria { get; set; }

        [JsonProperty(PropertyName = "idCategoria")]
        public int IDCategoria { get; set; }

        [JsonProperty(PropertyName = "categoriaDescricao")]
        public string CategoriaDescricao { get; set; }

        [JsonProperty(PropertyName = "descricao")]
        public string Descricao { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Controllers/ProdutosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Sistema.TSTOnline.Domain.Entities.Cadastros;
using Sistema.TSTOnline.Domain.Entities.Produtos;
using Sistema.TSTOnline.Domain.Interfaces;
using Sistema.TSTOnline.Domain.Services.Produtos;
using Sistema.TSTOnline.Web.Models.Produtos;
using System.Linq;
using Sistema.TSTOnline.Domain.Services.Estoque;
using Sistema.TSTOnline.Domain.Services.Usuario;
using System.Collections.Generic;

namespace Sistema.TSTOnline.Web.Controllers
{
    [Route("[controller]")]
    [AllowAnonymous]
    public class ProdutosController : Controller
    {
        #region Variables

        private readonly IRepository<CategoriaEN> _categoriaRepository;
        private readonly CategoriaBU _categoriaBU;

        private readonly IRepository<SubCategoriaEN> _subCategoriaRepository;
        private readonly SubCategoriaBU _subCategoriaBU;

        private readonly IRepository<ProdutoEN> _produtoRepository;
        private readonly ProdutoBU _produtoBU;

        private readonly IRepository<FornecedorEN> _fornecedorRepository;

        private readonly UsuarioService _usuarioService;

        private int idCompany => _usuarioService.GetCompanyId();

        private int idUser => _usuarioService.GetUserId();

        #endregion Variables

        #region Constructor

        public ProdutosController(
                IRepository<CategoriaEN> categoriaRepository, CategoriaBU categoriaBU,
                IRepository<SubCategoriaEN> subCategoriaRepository, SubCategoriaBU subCategoriaBU,
                IRepository<ProdutoEN> produtoRepository, ProdutoBU produtoBU,
                IRepository<FornecedorEN> fornecedorRepository,
                UsuarioService usuarioService
            )
        {
            _categoriaRepository = categoriaRepository;
            _categoriaBU = categoriaBU;

            _subCategoriaRepository = subCategoriaRepository;
            _subCategoriaBU = subCategoriaBU;

            _produtoRepository = produtoRepository;
            _produtoBU = produtoBU;

            _fornecedorRepository = fornecedorRepository;

            _usuarioService = usuarioService;
        }

        #endregion Constructor

        #region Categorias

        [HttpGet]
        [Route("categoria")]
        public IActionResult Categoria(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("categoriaAddEdit/{idCategoria?}")]
        public IActionResult CategoriaAddEdit(int? idCategoria)
        {
            if (idCategoria != null)
            {
                var categoria = _categoriaRepository.GetByID(idCategoria ?? 0);

                var categoriaVM = new CategoriaVM()
                {
                    IDCategoria = categoria.IDCategoria,
                    Descricao = categoria.Descricao
                };

                return View(categoriaVM);
            }

            return View();
        }

        [HttpGet]
        [Route("listCategorias")]
        public JsonResult ListCategorias()
        {
            var listCategoria = _categoriaRepository.Where(obj => obj.IDCompany == idCompany).ToList();
            var categoriaVM = listCategoria.Select(
                c => new CategoriaVM
                {
                    IDCategoria = c.IDCategoria,
                    Descricao = c.Descricao
                });

            return Json(categoriaVM.ToList());
        }

        [HttpPost]
        [Route("categoriaCreateOrUpdate")]
        public IActionResult CategoriaCreateOrUpdate(CategoriaVM categoriaVM)
        {
            _categoriaBU.Save
                (
                    categoriaVM.IDCategoria,
                    idCompany,
                    idUser,
                    categoriaVM.Descricao
               );

            return Ok();
        }

        [HttpDelete]
        [Route("categoriaDelete/{id}")]
        public IActionResult CategoriaDelete(int id)
        {
            _categoriaRepository.Delete(id);

            return Ok();
        }

        #endregion Categorias

        #region Sub Categorias

        [HttpGet]
        [Route("subCategoria")]
        public IActionResult SubCategoria(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("subCategoriaAddEdit/{idSubCategoria?}")]
        public IActionResult SubCategoriaAddEdit(int? idSubCategoria)
        {
            if (idSubCategoria != null)
            {
                var subCategoria = _subCategoriaRepository.GetByID(idSubCategoria ?? 0);

                var subCategoriaVM = new SubCategoriaVM()
                {
                    IDSubCategoria = subCategoria.IDSubCategoria,
                    IDCategoria = subCategoria.IDCategoria,
                    Descricao = subCategoria.Descricao
                };

                return View(subCategoriaVM);
            }

            return View();
        }

        [HttpGet]
        [Route("listSubCategorias")]
        public JsonResult ListSubCategorias()
        {
            var listSubCategoria = _subCategoriaRepository.Where(obj => obj.IDCompany == idCompany).ToList();
            var subCategoriaVM = listSubCategoria.Select(
                c => new SubCategoriaVM
                {
                    IDSubCategoria = c.IDSubCategoria,
                    IDCategoria = c.IDCategoria,
                    CategoriaDescricao = _categoriaRepository.GetByID(c.IDCategoria)?.Descricao ?? string.Empty,
                    Descricao = c.Descricao
                });

            return Json(subCategoriaVM.ToList());
        }

        [HttpPost]
        [Route("subCategoriaCreateOrUpdate")]
        public IActionResult SubCategoriaCreateOrUpdate(SubCategoriaVM subCategoriaVM)
        {
            _subCategoriaBU.Save
                (
                    subCategoriaVM.IDSubCategoria,
                    idCompany,
                    idUser,
                    subCategoriaVM.IDCategoria,
                    subCategoriaVM.Descricao
               );

            return Ok();
        }

        [HttpDelete]
        [Route("subCategoriaDelete/{id}")]
        public IActionResult SubCategoriaDelete(int id)
        {
            _subCategoriaRepository.Delete(id);

            return Ok();
        }

        #endregion Sub Categorias

        #region Produtos

        [HttpGet]
        [Route("produto")]
        public IActionResult Produto(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("produtoAddEdit/{idProduto?}")]
        public IActionResult ProdutoAddEdit(int? idProduto)
        {
            if (idProduto != null)
            {
                var produto = _produtoRepository.GetByID(idProduto ?? 0);

                var produtoVM = new ProdutoVM()
                {
                    IDProduto = produto.IDProduto,
                    SKU = produto.SKU,
                    Nome = produto.Nome,
                    Descricao = produto.Descricao,
                    IDFornecedor = produto.IDFornecedor,
                    FornecedorRazaoSocial = _fornecedorRepository.GetByID(produto.IDFornecedor)?.RazaoSocial ?? string.Empty,
                    IDCategoria = produto.IDCategoria,
                    CategoriaDescricao = _categoriaRepository.GetByID(produto.IDCategoria)?.Descricao ?? string.Empty,
                    IDSubCategoria = produto.IDSubCategoria,
                    SubCategoriaDescricao = _subCategoriaRepository.GetByID(produto.IDSubCategoria)?.Descricao ?? string.Empty,
                    Preco = produto.Preco
                };

                return View(produtoVM);
            }

            return View();
        }

        [HttpGet]
        [Route("listProdutos")]
        public JsonResult ListProdutos()
        {
            var listProdutos = _produtoRepository.Where(obj => obj.IDCompany == idCompany).ToList();

            List<ProdutoVM> listProdutoVM = new List<ProdutoVM>();

            foreach (var itemProduto in listProdutos)
            {
                ProdutoVM produtoVM = new ProdutoVM()
                {
                    IDProduto = itemProduto.IDProduto,
                    SKU = string.Empty,
                    Nome = itemProduto.Nome,
                    Descricao = itemProduto.Descricao,
                    IDFornecedor = itemProduto.IDFornecedor,
                    FornecedorRazaoSocial = _fornecedorRepository.GetByID(itemProduto.IDFornecedor)?.RazaoSocial ?? string.Empty,
                    IDCategoria = itemProduto.IDCategoria,
                    CategoriaDescricao = _categoriaRepository.GetByID(itemProduto.IDCategoria)?.Descricao ?? string.Empty,
                    IDSubCategoria = itemProduto.IDSubCategoria,
                    SubCategoriaDescricao = _subCategoriaRepository.GetByID(itemProduto.IDSubCategoria)?.Descricao ?? string.Empty,
                    Preco = itemProduto.Preco
                };
                
                listProdutoVM.Add(produtoVM);
            }

            return Json(listProdutoVM.ToList());
        }

        [HttpPost]
        [Route("produtoCreateOrUpdate")]
        public IActionResult ProdutoCreateOrUpdate([FromBody] ProdutoVM produtoVM)
        {
            _produtoBU.Save
                (
                    produtoVM.IDProduto,
                    idCompany,
                    idUser,
                    produtoVM.SKU,
                    produtoVM.Nome,
                    produtoVM.Descricao,
                    produtoVM.IDFornecedor,
                    produtoVM.IDCategoria,
                    produtoVM.IDSubCategoria,
                    produtoVM.Preco
               );

            return Ok();
        }

Site/src/Sistema.TSTOnline.Web/Views/Produtos/Categoria.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "CATEGORIAS";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <a href="/produtos/CategoriaAddEdit" class="btn btn-primary">
            <i class="fa fa-plus fa-lg"></i> Nova Categoria
        </a>
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblCategoria" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Código</th>
                <th width="50%" data-column-id="descricao">Descrição</th>
                <th width="10%" data-column-id="commands1">Editar</th>
                <th width="10%" data-column-id="commands3">Delete</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

@await Html.PartialAsync("~/Views/Shared/_ConfirmActionPartial.cshtml", 0)

@section Scripts{
    <script src="~/js/produtos/categoria.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/Produtos/CategoriaAddEdit.cshtml
@model Sistema.TSTOnline.Web.Models.Produtos.CategoriaVM
@using Sistema.TSTOnline.Domain.Services.Usuario

@inject UsuarioService _usuarioService

@{
    int idCompany = _usuarioService.GetCompanyId();
    var newRegister = Model == null;
    var labelButton = "Cadastrar Categoria";

    if (newRegister)
    {
        ViewData["Title"] = "NOVA CATEGORIA";
    }
    else
    {
        ViewData["Title"] = "EDITAR CATEGORIA";
        labelButton = "Atualizar Categoria";
    }
}

<form id="frmCategoria" asp-action="CategoriaCreateOrUpdate" asp-controller="Produtos"
      data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location='/produtos/categoria'">
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DA CATEGORIA</span></h5>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-2 col-lg-2">
                        @Html.HiddenFor(m => m.IDCategoria, new { id = "idCategoria" })
                        @Html.TextBoxFor(m => m.IDCategoria, new { @class = "form-control", @placeholder = "Código", @disabled = "disabled" })
                    </div>

                    <div class="col-sm-10 col-lg-10">
                        @Html.TextBoxFor(m => m.Descricao, new { @class = "form-control", @maxlength = "200", @placeholder = "Descrição", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save fa-lg"></i> @labelButton
                            </button>
                            <button type="button" onclick="javascript:window.location='/produtos/categoria?idCompany=@idCompany'" class="btn btn-danger">
                                <i class="fas fa-undo fa-lg"></i> Voltar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Site/src/Sistema.TSTOnline.Web/Views/Produtos/Produto.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "PRODUTOS";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <a href="/produtos/ProdutoAddEdit" class="btn btn-primary">
            <i class="fa fa-plus fa-lg"></i> Novo Produto
        </a>
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblProduto" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Código</th>
                @*<th width="10%" data-column-id="sku">SKU</th>*@
                <th width="20%" data-column-id="nome">Nome</th>
                <th width="20%" data-column-id="fornecedorNome">Fornecedor</th>
                <th width="15%" data-column-id="categoriaDescricao">Categoria</th>
                <th width="15%" data-column-id="preco">Preço</th>
                <th width="10%" data-column-id="commands1">Editar</th>
                <th width="10%" data-column-id="commands3">Delete</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

@await Html.PartialAsync("~/Views/Shared/_ConfirmActionPartial.cshtml", 0)

@section Scripts{
    <script src="~/js/produtos/produto.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/Produtos/ProdutoAddEdit.cshtml
@model Sistema.TSTOnline.Web.Models.Produtos.ProdutoVM
@using Sistema.TSTOnline.Domain.Interfaces
@using Sistema.TSTOnline.Domain.Entities.Cadastros
@using Sistema.TSTOnline.Domain.Entities.Produtos
@using Sistema.TSTOnline.Domain.Services.Usuario
@using Sistema.TSTOnline.Domain.Utils

@inject IRepository<FornecedorEN> _fornecedorRepository
@inject IRepository<CategoriaEN> _categoriaRepository
@inject IRepository<SubCategoriaEN> _subCategoriaRepository
@inject UsuarioService _usuarioService

@{
    var newRegister = Model == null;
    var labelButton = "Cadastrar Produto";

    if (newRegister)
    {
        ViewData["Title"] = "NOVO PRODUTO";
    }
    else
    {
        ViewData["Title"] = "EDITAR PRODUTO";
        labelButton = "Atualizar Produto";
    }
    
    int idCompany = _usuarioService.GetCompanyId();
    var listFornecedores = _fornecedorRepository.Where(obj => obj.IDCompany == idCompany).ToList();
    var listCategorias = _categoriaRepository.Where(obj => obj.IDCompany == idCompany).ToList();
    var listSubCategorias = _subCategoriaRepository.Where(obj => obj.IDCompany == idCompany).ToList();
}

<form id="frmProduto">
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DO PRODUTO</span></h5>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-2 col-lg-2">
                        @Html.HiddenFor(m => m.IDProduto, new { id = "idProduto" })
                        @Html.TextBoxFor(m => m.IDProduto, new { @class = "form-control", @placeholder = "Código", @disabled = "disabled" })
                    </div>

                    @*<div class="col-sm-3 col-lg-4">
                            @Html.TextBoxFor(m => m.SKU, new { @class = "form-control", @maxlength = "45", @placeholder = "SKU", @required = "true" })
                        </div>*@

                    <div class="col-sm-10 col-lg-10">
                        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", @maxlength = "50", @placeholder = "Nome", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-12 col-lg-12">
                        @Html.TextAreaFor(m => m.Descricao, new { @class = "form-control", @placeholder = "Descrição", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-3 col-lg-3">
                        <select name="idFornecedor" class="form-control" required="">

                            @if (newRegister)
                            {
                                <option selected disabled>Escolha um Fornecedor</option>
                            }

                            @foreach (var itemFornecedor in listFornecedores)
                            {
                                @if (newRegister)
                                {
                                    <option select value="@itemFornecedor.IDFornecedor">@itemFornecedor.NomeFantasia</option>
                                }
                                else if (Model.IDFornecedor == itemFornecedor.IDFornecedor)
                                {
                                    <option selected value="@itemFornecedor.IDFornecedor">@itemFornecedor.NomeFantasia</option>
                                }
                                else
                                {
                                    <option value="@itemFornecedor.IDFornecedor">@itemFornecedor.NomeFantasia</option>
                                }
                            }
                        </select>
                    </div>
                    <div class="col-sm-3 col-lg-3">
                        <select name="idCategoria" class="form-control" required="">

                            @if (newRegister)
                            {
                                <option selected disabled>Escolha uma Categoria</option>
                            }

                            @foreach (var itemCategoria in listCategorias)
                            {
                                @if (newRegister)
                                {
                                    <option select value="@itemCategoria.IDCategoria">@itemCategoria.Descricao</option>
                                }
                                else if (Model.IDCategoria == itemCategoria.IDCategoria)
                                {
                                    <option selected value="@itemCategoria.IDCategoria">@itemCategoria.Descricao</option>
                                }
                                else
                                {
                                    <option value="@itemCategoria.IDCategoria">@itemCategoria.Descricao</option>
                                }
                            }
                        </select>
                    </div>
                    <div class="col-sm-3 col-lg-3">
                        <select name="idSubCategoria" class="form-control" required="">

                            @if (newRegister)
                            {
                                <option selected disabled>Escolha uma Sub-Categoria</option>
                            }

                            @foreach (var itemSubCategoria in listSubCategorias)
                            {
                                @if (newRegister)
                                {
                                    <option select value="@itemSubCategoria.IDSubCategoria">@itemSubCategoria.Descricao</option>
                                }
                                else if (Model.IDSubCategoria == itemSubCategoria.IDSubCategoria)
                                {
                                    <option selected value="@itemSubCategoria.IDSubCategoria">@itemSubCategoria.Descricao</option>
                                }
                                else
                                {
                                    <option value="@itemSubCategoria.IDSubCategoria">@itemSubCategoria.Descricao</option>
                                }
                            }
                        </select>
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        <div class="input-group mb-3">
                            <span class="input-group-text">R$</span>
                            @Html.TextBoxFor(m => m.Preco, new { id = "txtPreco", name = "txtPreco", @class = "form-control", @maxlength = "20", @placeholder = "Preço", @required = "true" })
                        </div>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save fa-lg"></i> @labelButton
                            </button>
                            <button type="button" onclick="javascript:window.location='/produtos/produto?idCompany=@idCompany'" class="btn btn-danger">
                                <i class="fas fa-undo fa-lg"></i> Voltar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


@section Scripts{

    <script src="~/js/produtos/produto.js?v=@Helper.GetVersion()"></script>

    <script>
        $(function () {
            $('#txtPreco').mask("#.##0,00", { reverse: true });
        });
    </script>
}

Site/src/Sistema.TSTOnline.Web/Views/Produtos/SubCategoria.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "SUB CATEGORIAS";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <a href="/produtos/SubCategoriaAddEdit" class="btn btn-primary">
            <i class="fa fa-plus fa-lg"></i> Nova Sub-Categoria
        </a>
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblSubCategoria" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Código</th>
                <th width="30%" data-column-id="categoriaDescricao">Categoria</th>
                <th width="30%" data-column-id="descricao">Descrição</th>
                <th width="10%" data-column-id="commands1">Editar</th>
                <th width="10%" data-column-id="commands3">Delete</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

@await Html.PartialAsync("~/Views/Shared/_ConfirmActionPartial.cshtml", 0)

@section Scripts{
    <script src="~/js/produtos/subCategoria.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/Produtos/SubCategoriaAddEdit.cshtml
@model Sistema.TSTOnline.Web.Models.Produtos.SubCategoriaVM
@using Sistema.TSTOnline.Domain.Interfaces
@using Sistema.TSTOnline.Domain.Entities.Produtos
@using Sistema.TSTOnline.Domain.Services.Usuario

@inject IRepository<CategoriaEN> _categoriaRepository
@inject UsuarioService _usuarioService

@{
    var newRegister = Model == null;
    var labelButton = "Cadastrar Sub-Categoria";

    if (newRegister)
    {
        ViewData["Title"] = "NOVA SUB-CATEGORIA";
    }
    else
    {
        ViewData["Title"] = "EDITAR SUB-CATEGORIA";
        labelButton = "Atualizar Sub-Categoria";
    }
    
    int idCompany = _usuarioService.GetCompanyId();
    var listCategorias = _categoriaRepository.Where(obj => obj.IDCompany == idCompany).ToList();
}

<form id="frmSubCategoria" asp-action="SubCategoriaCreateOrUpdate" asp-controller="Produtos"
      data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location='/produtos/subcategoria'">
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DA SUB-CATEGORIA</span></h5>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-2 col-lg-2">
                        @Html.HiddenFor(m => m.IDSubCategoria, new { id = "idSubCategoria" })
                        @Html.TextBoxFor(m => m.IDSubCategoria, new { @class = "form-control", @placeholder = "Código", @disabled = "disabled" })
                    </div>

                    <div class="col-sm-10 col-lg-10">
                        <select name="idCategoria" class="form-control" required="">

                            @if (newRegister)
                            {
                                <option selected disabled>Escolha uma Categoria</option>
                            }

                            @foreach (var itemCategoria in listCategorias)
                            {
                                @if (newRegister)
                                {
                                    <option select value="@itemCategoria.IDCategoria">@itemCategoria.Descricao</option>
                                }
                                else if (Model.IDCategoria == itemCategoria.IDCategoria)
                                {
                                    <option selected value="@itemCategoria.IDCategoria">@itemCategoria.Descricao</option>
                                }
                                else
                                {
                                    <option value="@itemCategoria.IDCategoria">@itemCategoria.Descricao</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-12 col-lg-12">
                        @Html.TextBoxFor(m => m.Descricao, new { @class = "form-control", @maxlength = "200", @placeholder = "Descrição", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save fa-lg"></i> @labelButton
                            </button>
                            <button type="button" onclick="javascript:window.location='/produtos/subcategoria?idCompany=@idCompany'" class="btn btn-danger">
                                <i class="fas fa-undo fa-lg"></i> Voltar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>