Site/src/Sistema.TSTOnline.Web/Models/MovimentacaoFinanceira/ContasReceberVM.cs
using System;
using Newtonsoft.Json;
using Sistema.TSTOnline.Domain.Utils;

namespace Sistema.TSTOnline.Web.Models.MovimentacaoFinanceira
{
    public class ContasReceberVM
    {
        [JsonProperty(PropertyName = "idContasReceber")]
        public int IDContasReceber { get; set; }

        [JsonProperty(PropertyName = "dataCadastro")]
        public DateTime DataCadastro { get; set; }

        [JsonProperty(PropertyName = "idEmpresa")]
        public int IDEmpresa { get; set; }

        [JsonProperty(PropertyName = "razaoSocial")]
        public string RazaoSocial { get; set; }

        [JsonProperty(PropertyName = "numeroTitulo")]
        public string NumeroTitulo { get; set; }

        [JsonProperty(PropertyName = "seq")]
        public int Seq { get; set; }

        [JsonProperty(PropertyName = "dataVencimento")]
        public DateTime DataVencimento { get; set; }

        [JsonProperty(PropertyName = "valor")]
        public decimal Valor { get; set; }

        [JsonProperty(PropertyName = "valorPago")]
        public decimal ValorPago { get; set; }

        [JsonProperty(PropertyName = "origem")]
        public OrigemContasReceberEnum Origem { get; set; }

        [JsonProperty(PropertyName = "origemDescricao")]
        public string OrigemDescricao { get { return Origem.ToDescriptionEnum(); } }

        [JsonProperty(PropertyName = "chave")]
        public int Chave { get; set; }

        [JsonProperty(PropertyName = "linkFatura")]
        public string LinkFatura { get; set; }

        [JsonProperty(PropertyName = "status")]
        public ContasReceberStatusEnum Status { get; set; }

        [JsonProperty(PropertyName = "statusDescricao")]
        public string StatusDescricao { get { return Status.ToDescriptionEnum(); } }

        [JsonProperty(PropertyName = "observacao")]
        public string Observacao { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Models/MovimentacaoFinanceira/FluxoCaixaVM.cs
using System;
using Newtonsoft.Json;
using Sistema.TSTOnline.Domain.Utils;

namespace Sistema.TSTOnline.Web.Models.MovimentacaoFinanceira
{
    public class FluxoCaixaVM
    {
        [JsonProperty(PropertyName = "idFluxoCaixa")]
        public int IDFluxoCaixa { get; set; }

        [JsonProperty(PropertyName = "dataLancamento")]
        public DateTime DataLancamento { get; set; }

        [JsonProperty(PropertyName = "tipoLancamento")]
        public TipoLancamentoFluxoCaixaEnum TipoLancamento { get; set; }

        [JsonProperty(PropertyName = "tipoLancamentoDescricao")]
        public string TipoLancamentoDescricao { get { return TipoLancamento.ToDescriptionEnum(); } }

        [JsonProperty(PropertyName = "origem")]
        public OrigemFluxoCaixaEnum Origem { get; set; }

        [JsonProperty(PropertyName = "origemDescricao")]
        public string OrigemDescricao { get { return Origem.ToDescriptionEnum(); } }

        [JsonProperty(PropertyName = "chave")]
        public int Chave { get; set; }

        [JsonProperty(PropertyName = "pedidoVendaNumero")]
        public string PedidoVendaNumero { get; set; }

        [JsonProperty(PropertyName = "contasReceberParcela")]
        public string ContasReceberParcela { get; set; }

        [JsonProperty(PropertyName = "razaoSocial")]
        public string RazaoSocial { get; set; }

        [JsonProperty(PropertyName = "valor")]
        public decimal Valor { get; set; }

        [JsonProperty(PropertyName = "observacao")]
        public string Observacao { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Controllers/MovimentacaoFinanceiraController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Sistema.TSTOnline.Domain.Entities.Cadastros;
using Sistema.TSTOnline.Domain.Entities.MovimentacaoFinanceira;
using Sistema.TSTOnline.Domain.Interfaces;
using Sistema.TSTOnline.Domain.Services.Fluxo;
using Sistema.TSTOnline.Domain.Services.MovimentacaoFinanceira;
using Sistema.TSTOnline.Domain.Services.Template;
using Sistema.TSTOnline.Domain.Services.Usuario;
using Sistema.TSTOnline.Domain.Utils;
using Sistema.TSTOnline.Web.Models.MovimentacaoFinanceira;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Sistema.TSTOnline.Web.Controllers
{
    [Route("[controller]")]
    [AllowAnonymous]
    public class MovimentacaoFinanceiraController : Controller
    {
        #region Variables

        private readonly IRepository<ContasReceberEN> _contasReceberRepository;
        private readonly ContasReceberBU _contasReceberBU;
        private readonly IRepository<ContasReceberGrid> _listContasReceberRepository;
        private readonly IRepository<EmpresaEN> _empresaRepository;

        private readonly IRepository<FluxoCaixaEN> _fluxoCaixaRepository;
        private readonly FluxoCaixaBU _fluxoCaixaBU;
        private readonly IRepository<FluxoCaixaGrid> _listFluxoCaixaRepository;

        private readonly FluxoBU _fluxoBU;

        private readonly IConfiguration _configuration;

        private readonly TemplateBU _templateBU;

        private readonly UsuarioService _usuarioService;

        private int idCompany => _usuarioService.GetCompanyId();

        private int idUser => _usuarioService.GetUserId();

        #endregion Variables

        #region Constructor

        public MovimentacaoFinanceiraController
            (
                IRepository<ContasReceberEN> contasReceberRepository, ContasReceberBU contasReceberBU,
                IRepository<ContasReceberGrid> listContasReceberRepository,
                IRepository<EmpresaEN> empresaRepository,
                IRepository<FluxoCaixaEN> fluxoCaixaRepository, FluxoCaixaBU fluxoCaixaBU,
                IRepository<FluxoCaixaGrid> listFluxoCaixaRepository,
                FluxoBU fluxoBU,
                IConfiguration configuration,
                TemplateBU templateBU,
                UsuarioService usuarioService
            )
        {
            _contasReceberRepository = contasReceberRepository;
            _contasReceberBU = contasReceberBU;
            _listContasReceberRepository = listContasReceberRepository;

            _empresaRepository = empresaRepository;

            _fluxoCaixaRepository = fluxoCaixaRepository;
            _fluxoCaixaBU = fluxoCaixaBU;
            _listFluxoCaixaRepository = listFluxoCaixaRepository;

            _fluxoBU = fluxoBU;

            _configuration = configuration;

            _templateBU = templateBU;

            _usuarioService = usuarioService;
        }

        #endregion Constructor

        #region Contas a Receber

        [HttpGet]
        [Route("contasReceber")]
        public IActionResult ContasReceber(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("contasReceberAddEdit/{idContasReceber?}")]
        public IActionResult ContasReceberAddEdit(int? idContasReceber)
        {
            if (idContasReceber != null)
            {
                var contasReceber = _contasReceberRepository.GetByID(idContasReceber ?? 0);

                var contasReceberVM = new ContasReceberVM()
                {
                    IDContasReceber = contasReceber.IDContasReceber,
                    DataCadastro = contasReceber.DataCadastro,
                    IDEmpresa = contasReceber.IDEmpresa,
                    RazaoSocial = _empresaRepository.GetByID(contasReceber.IDEmpresa).RazaoSocial,
                    NumeroTitulo = contasReceber.NumeroTitulo,
                    Seq = contasReceber.Seq,
                    DataVencimento = contasReceber.DataVencimento,
                    Valor = contasReceber.Valor,
                    ValorPago = contasReceber.ValorPago,
                    Origem = contasReceber.Origem,
                    Chave = contasReceber.Chave,
                    LinkFatura = contasReceber.LinkFatura,
                    Status = contasReceber.Status,
                    Observacao = contasReceber.Observacao
                };

                return View(contasReceberVM);
            }

            return View();
        }

        [HttpGet]
        [Route("listContasReceber")]
        public JsonResult ListContasReceber()
        {
            string SQL = $@"select
                                ctr.idcontasreceber as id,
                                ctr.idcontasreceber as idContasReceber,
                                emp.razaosocial     as razaoSocial,
                                ctr.numerotitulo    as numeroTitulo,
                                ctr.seq             as seq,
                                ctr.datavencimento  as dataVencimento,
                                ctr.valor           as valor,
                                ctr.valorpago       as valorPago,
                                ctr.status          as Status,
                                ctr.linkfatura      as linkFatura

                              from tbcontasreceber ctr
                             inner join tbcadempresas emp on ctr.idempresa = emp.idempresa
                             where ctr.idcompany = {idCompany}";

            var listContasReceber = _listContasReceberRepository.FromSql(SQL).OrderByDescending(e => e.IDContasReceber).ToList();

            return Json(listContasReceber.ToList());
        }

        [HttpPost]
        [Route("contasReceberCreateOrUpdate")]
        public IActionResult ContasReceberCreateOrUpdate(ContasReceberVM contasReceberVM)
        {
            if ((int)contasReceberVM.Origem == 0)
                contasReceberVM.Origem = OrigemContasReceberEnum.ContasReceber;

            if (contasReceberVM.Seq == 0)
                contasReceberVM.Seq = 1;

            _contasReceberBU.Save
                (
                    contasReceberVM.IDContasReceber,
                    idCompany,
                    idUser,
                    contasReceberVM.IDEmpresa,
                    contasReceberVM.NumeroTitulo,
                    contasReceberVM.Seq,
                    contasReceberVM.DataVencimento,
                    contasReceberVM.Valor,
                    contasReceberVM.ValorPago,
                    contasReceberVM.Origem,
                    contasReceberVM.LinkFatura,
                    contasReceberVM.Chave,
                    contasReceberVM.Observacao
               );

            return Ok();
        }

        [HttpPut]
        [Route("alterarStatusContasReceber/{id}/{status}")]
        public IActionResult ContasReceberAlterarStatus(int id, ContasReceberStatusEnum Status)
        {
            _fluxoBU.FluxoContasReceber(id, Status);

            return Ok();
        }

        [HttpPost]
        [Route("baixarListaTitulos")]
        public IActionResult BaixarListaTitulos([FromBody] List<ContasReceberVM> listTitulos)
        {
            foreach (var itemTitulo in listTitulos)
            {
                _fluxoBU.FluxoContasReceber(itemTitulo.IDContasReceber, ContasReceberStatusEnum.Baixado);
            }

            return Ok();
        }

        [HttpPut]
        [Route("contasReceberGerarFatura/{id}")]
        public IActionResult ContasReceberGerarFatura(int id)
        {
            string emailCopia = _configuration.GetSection("Environment:Email").Value;
            _fluxoBU.GerarFatura(id, emailCopia);

            return Ok();
        }

        #endregion Contas a Receber

        #region Fluxo de Caixa

        [HttpGet]
        [Route("fluxoCaixa")]
        public IActionResult FluxoCaixa(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("fluxoCaixaAddEdit/{idFluxoCaixa?}")]
        public IActionResult FluxoCaixaAddEdit(int? idFluxoCaixa)
        {
            if (idFluxoCaixa != null)
            {
                var fluxoCaixa = _fluxoCaixaRepository.GetByID(idFluxoCaixa ?? 0);

                var fluxoCaixaVM = new FluxoCaixaVM()
                {
                    IDFluxoCaixa = fluxoCaixa.IDFluxoCaixa,
                    DataLancamento = fluxoCaixa.DataLancamento,
                    TipoLancamento = fluxoCaixa.TipoLancamento,
                    Origem = fluxoCaixa.Origem,
                    Chave = fluxoCaixa.Chave,
                    Valor = fluxoCaixa.Valor,
                    Observacao = fluxoCaixa.Observacao
                };

                return View(fluxoCaixaVM);
            }

            return View();
        }

        [HttpGet]
        [Route("listFluxoCaixa")]
        public JsonResult ListFluxoCaixa()
        {
            string SQL = $@"select
                                flc.idfluxocaixa            as id,
                                flc.idfluxocaixa            as idFluxoCaixa,
                                flc.datalancamento          as dataLancamento,
                                flc.tipolancamento          as tipoLancamento,
                                flc.origem                  as origem,
                                lpad(ped.idpedido, 5, '0')  as pedidoVendaNumero,
                                lpad(ctr.seq, 2, '0')       as contasReceberParcela,
                                emp.razaosocial             as razaoSocial,
                                flc.valor                   as valor

                              from tbfluxocaixa flc
                              left join tbcontasreceber ctr on flc.chave      = ctr.idcontasreceber

Site/src/Sistema.TSTOnline.Web/Views/MovimentacaoFinanceira/ContasReceber.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "CONTAS A RECEBER";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <a href="/movimentacaofinanceira/contasReceberAddEdit" class="btn btn-primary">
            <i class="fa fa-plus fa-lg"></i> Novo Título
        </a>
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
        <button class="btn btn-warning" id="btnBaixarTitulos"><i class="fa fa-download fa-lg"></i> <b> Baixar Títulos Selecionados</b></button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblContasReceber" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Sel</th>
                <th data-column-id="id" data-type="numeric">Código</th>
                <th width="15%" data-column-id="razaoSocial">Cliente</th>
                <th width="10%" data-column-id="numeroTitulo">Título</th>
                <th width="05%" data-column-id="numeroSeq">Seq</th>
                <th width="15%" data-column-id="dataVencimento">Data Vencimento</th>
                <th width="15%" data-column-id="valor">Valor</th>
                <th width="20%" data-column-id="valorPago">Valor Pago</th>
                <th width="15%" data-column-id="statusDescricao">Status</th>
                <th width="15%" data-column-id="linkFatura">Fatura</th>
                <th width="10%" data-column-id="commands1">Editar</th>
                <th width="10%" data-column-id="commands3">Baixar Titulo</th>
                <th width="10%" data-column-id="commands4">Cancelar</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

@await Html.PartialAsync("~/Views/Shared/_ConfirmActionPartial.cshtml", 1)

@await Html.PartialAsync("~/Views/Shared/_ConfirmActionPartial.cshtml", 3)

@await Html.PartialAsync("~/Views/Shared/_ConfirmActionPartial.cshtml", 4)

@section Scripts{
    <script src="~/js/movimentacaofinanceira/contasReceber.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/MovimentacaoFinanceira/ContasReceberAddEdit.cshtml
@model Sistema.TSTOnline.Web.Models.MovimentacaoFinanceira.ContasReceberVM
@using Sistema.TSTOnline.Domain.Services.Usuario
@using Sistema.TSTOnline.Domain.Utils

@inject UsuarioService _usuarioService

@{
    int idUser = _usuarioService.GetCompanyId();
    var newRegister = Model == null;
    var labelButton = "Cadastrar Novo Título";

    if (newRegister)
    {
        ViewData["Title"] = "NOVO TÍTULO";
    }
    else
    {
        ViewData["Title"] = "EDITAR TÍTULO";
        labelButton = "Atualizar Título";
    }

    var IDEmpresa = 0;
    bool disabled = false;
    if (Model != null)
    {
        IDEmpresa = Model.IDEmpresa;

        if (Model.Origem == OrigemContasReceberEnum.PedidoVenda)
        {
            disabled = true;
        }
    }
}

<form id="frmContasReceber" asp-action="ContasReceberCreateOrUpdate" asp-controller="MovimentacaoFinanceira"
      data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location='/movimentacaofinanceira/contasreceber'">
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DO TÍTULO</span></h5>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">

                    <div class="col-sm-2 col-lg-2">
                        @Html.HiddenFor(m => m.IDContasReceber, new { id = "idContasReceber" })
                        @Html.HiddenFor(m => m.Seq, new { id = "seq" })
                        @Html.HiddenFor(m => m.Chave, new { id = "chave" })
                        @Html.HiddenFor(m => m.Origem, new { id = "origem" })
                        @Html.TextBoxFor(m => m.IDContasReceber, new { @class = "form-control", @placeholder = "Código", @disabled = "disabled" })
                    </div>

                    <div class="col-sm-4 col-lg-4">
                        @Html.TextBoxFor(m => m.NumeroTitulo, @disabled ? (object)new { @class = "form-control", @readonly = "readonly" } : new { @class = "form-control", @maxlength = "45", @placeholder = "Número do Título", @required = "true" })
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        @Html.TextBoxFor(m => m.DataVencimento, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control", @title = "Data de Vencimento do Título", @data_toggle = "tooltip", @required = "true" })
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        <div class="input-group mb-3">
                            <span class="input-group-text">R$</span>
                            @Html.TextBoxFor(m => m.Valor, @disabled ? (object)new { @class = "form-control", @readonly = "readonly" } : new { id = "txtValor", name = "txtValor", @class = "form-control", @maxlength = "20", @placeholder = "Valor", @required = "true" })
                        </div>
                    </div>

                </div>

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DO CLIENTE</span></h5>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">

                    <div class="col-sm-1 col-lg-1">
                        @if (disabled)
                        {
                            <button type="button" class="btn btn-primary w-100" data-toggle="modal" data-target="#modalEmpresa" disabled><i class="fa fa-search fa-lg"></i></button>
                        }
                        else
                        {
                            <button type="button" class="btn btn-primary w-100" data-toggle="modal" data-target="#modalEmpresa"><i class="fa fa-search fa-lg"></i></button>
                        }
                    </div>

                    <div class="col-sm-11 col-lg-11">
                        @Html.TextBoxFor(m => m.RazaoSocial, @disabled ? (object)new { @class = "form-control", @disabled = "disabled" } : new { id = "RazaoSocial", @class = "form-control", @maxlength = "150", @placeholder = "Razão Social", @readonly = "readonly", @required = "true" })
                        <input type="hidden" name="idEmpresa" id="idEmpresa" value="@IDEmpresa">
                    </div>
                </div>

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">OBSERVAÇÕES</span></h5>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-12 col-lg-12">
                        @Html.TextAreaFor(m => m.Observacao, new { @class = "form-control", @placeholder = "Observação", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save fa-lg"></i> @labelButton
                            </button>
                            <button type="button" onclick="javascript:window.location='/movimentacaofinanceira/contasreceber'" class="btn btn-danger">
                                <i class="fas fa-undo fa-lg"></i> Voltar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@await Html.PartialAsync("~/Views/Shared/_BuscarEmpresaPartial.cshtml")


@section Scripts{

    <script src="~/js/cadastros/empresaPesquisa.js?v=@Helper.GetVersion()"></script>

    <script>
        $(function () {
            $('#txtValor').mask("#.##0,00", { reverse: true });
        });
    </script>
}

Site/src/Sistema.TSTOnline.Web/Views/MovimentacaoFinanceira/FluxoCaixa.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "FLUXO DE CAIXA";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <a href="/movimentacaofinanceira/fluxoCaixaAddEdit" class="btn btn-primary">
            <i class="fa fa-plus fa-lg"></i> Novo Lançamento
        </a>
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblFluxoCaixa" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Código</th>
                <th width="15%" data-column-id="dataLancamento">Data Lançamento</th>
                <th width="15%" data-column-id="tipoLancamentoDescricao">Tipo Lançamento</th>
                <th width="15%" data-column-id="origemDescricao">Origem</th>
                <th width="15%" data-column-id="pedidoVendaNumero">Pedido Venda</th>
                <th width="15%" data-column-id="contasReceberParcela">Parcela</th>
                <th width="15%" data-column-id="razaoSocial">Cliente</th>
                <th width="15%" data-column-id="valor">Valor</th>
                <th width="10%" data-column-id="commands1">Editar</th>
                <th width="15%" data-column-id="commands2">Imprimir</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

@section Scripts{
    <script src="~/js/movimentacaofinanceira/fluxoCaixa.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/MovimentacaoFinanceira/FluxoCaixaAddEdit.cshtml
@model Sistema.TSTOnline.Web.Models.MovimentacaoFinanceira.FluxoCaixaVM
@using Sistema.TSTOnline.Domain.Services.Usuario
@using Sistema.TSTOnline.Domain.Utils

@inject UsuarioService _usuarioService

@{
    int idUser = _usuarioService.GetCompanyId();
    var newRegister = Model == null;
    var labelButton = "Cadastrar Novo Lançamento";

    if (newRegister)
    {
        ViewData["Title"] = "NOVO LANÇAMENTO";
    }
    else
    {
        ViewData["Title"] = "EDITAR LANÇAMENTO";
        labelButton = "Atualizar Lançamento";
    }

    var listTiposLancamento = Enum.GetValues(typeof(TipoLancamentoFluxoCaixaEnum)).Cast<TipoLancamentoFluxoCaixaEnum>().ToList();

    var tipoLancamento = TipoLancamentoFluxoCaixaEnum.Entrada;

    if (Model != null)
    {
        tipoLancamento = Model.TipoLancamento;
    }
}

<form id="frmFluxoCaixa" asp-action="FluxoCaixaCreateOrUpdate" asp-controller="MovimentacaoFinanceira"
      data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location='/movimentacaofinanceira/fluxocaixa'">
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DO LANÇAMENTO</span></h5>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">

                    <div class="col-sm-2 col-lg-2">
                        @Html.HiddenFor(m => m.IDFluxoCaixa, new { id = "idFluxoCaixa" })
                        @Html.TextBoxFor(m => m.IDFluxoCaixa, new { @class = "form-control", @placeholder = "Código", @disabled = "disabled" })
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        <select name="tipoLancamento" class="form-control" required="">

                            <option selected disabled>Tipo de Lançamento</option>

                            @foreach (var itemTipo in listTiposLancamento)
                            {
                                @if (newRegister)
                                {
                                    <option select value="@((int)itemTipo)">@itemTipo.ToDescriptionEnum()</option>
                                }
                                else if (Model.TipoLancamento == itemTipo)
                                {
                                    <option selected value="@((int)itemTipo)">@itemTipo.ToDescriptionEnum()</option>
                                }
                                else
                                {
                                    <option select value="@((int)itemTipo)">@itemTipo.ToDescriptionEnum()</option>
                                }
                            }
                        </select>
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        @Html.TextBoxFor(m => m.DataLancamento, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control", @title = "Data do Lançamento", @data_toggle = "tooltip", @required = "true" })
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        <div class="input-group mb-3">
                            <span class="input-group-text">R$</span>
                            @Html.TextBoxFor(m => m.Valor, new { id = "txtValor", name = "txtValor", @class = "form-control", @maxlength = "45", @placeholder = "Valor", @required = "true" })
                        </div>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-12 col-lg-12">
                        @Html.TextAreaFor(m => m.Observacao, new { @class = "form-control", @placeholder = "Observação", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save fa-lg"></i> @labelButton
                            </button>
                            <button type="button" onclick="javascript:window.location='/movimentacaofinanceira/fluxocaixa'" class="btn btn-danger">
                                <i class="fas fa-undo fa-lg"></i> Voltar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@await Html.PartialAsync("~/Views/Shared/_BuscarEmpresaPartial.cshtml")


@section Scripts{
    <script src="~/js/cadastros/empresaPesquisa.js?v=@Helper.GetVersion()"></script>

    <script>
        $(function () {
            $('#txtValor').mask("#.##0,00", { reverse: true });
        });
    </script>
}