Site/src/Sistema.TSTOnline.Web/Models/Estoque/EstoqueVM.cs
using Newtonsoft.Json;

namespace Sistema.TSTOnline.Web.Models.Estoque
{
    public class EstoqueVM
    {
        [JsonProperty(PropertyName = "codigo")]
        public int IDProduto { get; set; }

        [JsonProperty(PropertyName = "sku")]
        public string SKU { get; set; }

        [JsonProperty(PropertyName = "produtoNome")]
        public string ProdutoNome { get; set; }

        [JsonProperty(PropertyName = "qtde")]
        public int Qtde { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Models/Estoque/MovimentoEstoqueVM.cs
using Sistema.TSTOnline.Domain.Utils;
using System;
using Newtonsoft.Json;

namespace Sistema.TSTOnline.Web.Models.Estoque
{
    public class MovimentoEstoqueVM
    {
        [JsonProperty(PropertyName = "codigo")]
        public int IDMovimento { get; set; }

        [JsonProperty(PropertyName = "dataMovimento")]
        public DateTime DataMovimento { get; set; }

        [JsonProperty(PropertyName = "origem")]
        public OrigemMovimentoEstoqueEnum Origem { get; set; }

        [JsonProperty(PropertyName = "origemDescricao")]
        public string OrigemDescricao { get { return Origem.ToDescriptionEnum(); } }

        [JsonProperty(PropertyName = "chave")]
        public int Chave { get; set; }

        [JsonProperty(PropertyName = "idProduto")]
        public int IDProduto { get; set; }

        [JsonProperty(PropertyName = "sku")]
        public string SKU { get; set; }

        [JsonProperty(PropertyName = "produtoNome")]
        public string ProdutoNome { get; set; }

        [JsonProperty(PropertyName = "tipo")]
        public TipoMovimentoEstoqueEnum Tipo { get; set; }

        [JsonProperty(PropertyName = "tipoDescricao")]
        public string TipoDescricao { get { return Tipo.ToDescriptionEnum(); } }

        [JsonProperty(PropertyName = "qtde")]
        public int Qtde { get; set; }

        [JsonProperty(PropertyName = "observacao")]
        public string Observacao { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Controllers/EstoqueController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Sistema.TSTOnline.Domain.Entities.Produtos;
using Sistema.TSTOnline.Domain.Entities.Estoque;
using Sistema.TSTOnline.Domain.Interfaces;
using Sistema.TSTOnline.Domain.Services.Estoque;
using Sistema.TSTOnline.Domain.Services.Usuario;
using Sistema.TSTOnline.Web.Models.Estoque;
using System.Linq;
using Sistema.TSTOnline.Domain.Utils;
using System.Collections.Generic;

namespace Sistema.TSTOnline.Web.Controllers
{
    [Route("[controller]")]
    [AllowAnonymous]
    public class EstoqueController : Controller
    {
        #region Variables

        private readonly IRepository<MovimentoEstoqueEN> _movimentoEstoqueRepository;
        private readonly MovimentoEstoqueBU _movimentoEstoqueBU;

        private readonly IRepository<EstoqueEN> _estoqueRepository;

        private readonly IRepository<ProdutoEN> _produtoRepository;

        private readonly UsuarioService _usuarioService;

        private int idCompany => _usuarioService.GetCompanyId();

        private int idUser => _usuarioService.GetUserId();

        #endregion Variables

        #region Constructor

        public EstoqueController(
                IRepository<MovimentoEstoqueEN> movimentoEstoqueRepository, MovimentoEstoqueBU movimentoEstoqueBU,
                IRepository<EstoqueEN> estoqueRepository, EstoqueBU estoqueBU,
                IRepository<ProdutoEN> produtoRepository,
                UsuarioService usuarioService
            )
        {
            _movimentoEstoqueRepository = movimentoEstoqueRepository;
            _movimentoEstoqueBU = movimentoEstoqueBU;

            _estoqueRepository = estoqueRepository;

            _produtoRepository = produtoRepository;

            _usuarioService = usuarioService;
        }

        #endregion Constructor

        #region Movimentação de Estoque

        [HttpGet]
        [Route("movimentoEstoque")]
        public IActionResult MovimentoEstoque(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("movimentoEstoqueAddEdit/{idMovimentoEstoque?}")]
        public IActionResult MovimentoEstoqueAddEdit(int? idMovimentoEstoque)
        {
            if (idMovimentoEstoque != null)
            {
                var movimentoEstoque = _movimentoEstoqueRepository.GetByID(idMovimentoEstoque ?? 0);

                var movimentoEstoqueVM = new MovimentoEstoqueVM()
                {
                    IDMovimento = movimentoEstoque.IDMovimento,
                    DataMovimento = movimentoEstoque.DataMovimento,
                    Origem = movimentoEstoque.Origem,
                    Chave = movimentoEstoque.Chave,
                    IDProduto = movimentoEstoque.IDProduto,
                    Tipo = movimentoEstoque.Tipo,
                    Qtde = movimentoEstoque.Qtde,
                    Observacao = movimentoEstoque.Observacao
                };

                return View(movimentoEstoqueVM);
            }

            return View();
        }

        [HttpGet]
        [Route("listMovimentoEstoque")]
        public JsonResult ListMovimentoEstoque()
        {
            var listMovimentoEstoque = _movimentoEstoqueRepository.Where(obj => obj.IDCompany == idCompany).ToList();
            var movimentoEstoqueVM = listMovimentoEstoque.Select(
                c => new MovimentoEstoqueVM
                {
                    IDMovimento = c.IDMovimento,
                    DataMovimento = c.DataMovimento,
                    Origem = c.Origem,
                    Chave = c.Chave,
                    IDProduto = c.IDProduto,
                    SKU = _produtoRepository.GetByID(c.IDProduto).SKU,
                    ProdutoNome = _produtoRepository.GetByID(c.IDProduto).Nome,
                    Tipo = c.Tipo,
                    Qtde = c.Qtde,
                    Observacao = c.Observacao
                });

            return Json(movimentoEstoqueVM.ToList());
        }

        [HttpPost]
        [Route("movimentoEstoqueCreateOrUpdate")]
        public IActionResult MovimentoEstoqueCreateOrUpdate(MovimentoEstoqueVM movimentoEstoqueVM)
        {
            _movimentoEstoqueBU.Save
                (
                    idCompany,
                    idUser,
                    OrigemMovimentoEstoqueEnum.MovimentacaoEstoque,
                    0,
                    movimentoEstoqueVM.IDProduto,
                    movimentoEstoqueVM.Tipo,
                    movimentoEstoqueVM.Qtde,
                    movimentoEstoqueVM.Observacao
               );

            return Ok();
        }

        #endregion Movimentação de Estoque

        #region Estoques

        [HttpGet]
        [Route("estoque")]
        public IActionResult Estoque(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("listEstoques")]
        public JsonResult ListEstoques()
        {
            var listEstoques = _estoqueRepository.Where(obj => obj.IDCompany == idCompany).ToList();

            List<EstoqueVM> listEstoqueVM = new List<EstoqueVM>();

            foreach (var itemEstoque in listEstoques)
            {
                var produto = _produtoRepository.GetByID(itemEstoque.IDProduto);

                if (produto != null) 
                {
                    EstoqueVM estoqueVM = new EstoqueVM() {
                        IDProduto = itemEstoque.IDProduto,
                        SKU = produto.SKU,
                        ProdutoNome = produto.Nome,
                        Qtde = itemEstoque.Qtde
                    };

                    listEstoqueVM.Add(estoqueVM);
                }
            }

            return Json(listEstoqueVM.ToList());
        }

        #endregion Estoques
    }
}

Site/src/Sistema.TSTOnline.Web/Views/Estoque/Estoque.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "ESTOQUES";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblEstoque" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Código</th>
                @*<th width="20%" data-column-id="sku">SKU</th>*@
                <th width="50%" data-column-id="nome">Produto</th>
                <th width="10%" data-column-id="qtde">Qtde</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

@section Scripts{
    <script src="~/js/estoque/estoque.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/Estoque/MovimentoEstoque.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "MOVIMENTAÇÃO DE ESTOQUE";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <a href="/estoque/MovimentoEstoqueAddEdit" class="btn btn-primary">
            <i class="fa fa-plus fa-lg"></i> Nova Movimentação
        </a>
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblMovimentoEstoque" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Código</th>
                <th width="10%" data-column-id="dataMovimento">Data Movimento</th>
                <th width="20%" data-column-id="origemDescricao">Origem</th>
                @*<th width="10%" data-column-id="sku">SKU</th>*@
                <th width="30%" data-column-id="nome">Produto</th>
                <th width="20%" data-column-id="tipoDescricao">Tipo</th>
                <th width="10%" data-column-id="qtde">Qtde</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

@section Scripts{
    <script src="~/js/estoque/movimentoEstoque.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/Estoque/MovimentoEstoqueAddEdit.cshtml
@model Sistema.TSTOnline.Web.Models.Estoque.MovimentoEstoqueVM
@using Sistema.TSTOnline.Domain.Interfaces
@using Sistema.TSTOnline.Domain.Entities.Produtos
@using Sistema.TSTOnline.Domain.Services.Usuario
@using Sistema.TSTOnline.Domain.Utils

@inject IRepository<ProdutoEN> _produtoRepository
@inject UsuarioService _usuarioService

@{
    int idCompany = _usuarioService.GetCompanyId();
    var labelButton = "Cadastrar Movimentação";
    ViewData["Title"] = "NOVA MOVIMENTAÇÃO";

    var listTipos = Enum.GetValues(typeof(TipoMovimentoEstoqueEnum)).Cast<TipoMovimentoEstoqueEnum>().ToList();
}

<form id="frmMovimentoEstqoue" asp-action="MovimentoEstoqueCreateOrUpdate" asp-controller="Estoque"
      data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location='/estoque/movimentoestoque'">
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DA MOVIMENTAÇÃO</span></h5>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">

                    <div class="col-sm-1 col-lg-1">
                        <button type="button" class="btn btn-primary w-100" data-toggle="modal" data-target="#modalProduto"><i class="fa fa-search fa-lg"></i></button>
                    </div>

                    <div class="col-sm-11 col-lg-11">
                        @Html.TextBoxFor(m => m.ProdutoNome, new { id = "ProdutoNome", @class = "form-control", @maxlength = "150", @placeholder = "Produto", @readonly = "readonly", @required = "true" })
                        <input type="hidden" name="idProduto" id="idProduto">
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-6 col-lg-6">
                        <select name="tipo" class="form-control" required="">

                            <option selected disabled>Tipo de Movimentação</option>

                            @foreach (var itemTipo in listTipos)
                                                                                                                {
                            <option select value="@((int)itemTipo)">@itemTipo.ToDescriptionEnum()</option>
}
                        </select>
                    </div>

                    <div class="col-sm-6 col-lg-6">
                        @Html.TextBoxFor(m => m.Qtde, new { @type = "number", @class = "form-control", @maxlength = "15", @placeholder = "Qtde", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-12 col-lg-12">
                        @Html.TextAreaFor(m => m.Observacao, new { @class = "form-control", @placeholder = "Observação" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save fa-lg"></i> @labelButton
                            </button>
                            <button type="button" onclick="javascript:window.location='/estoque/movimentoestoque?idCompany=@idCompany'" class="btn btn-danger">
                                <i class="fas fa-undo fa-lg"></i> Voltar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@await Html.PartialAsync("~/Views/Shared/_BuscarProdutoPartial.cshtml")


@section Scripts{
    <script src="~/js/produtos/produtoPesquisa.js?v=@Helper.GetVersion()"></script>
}