Site/src/Sistema.TSTOnline.Web/Models/OrdemServico/LocalServicoVM.cs
using Newtonsoft.Json;

namespace Sistema.TSTOnline.Web.Models.OrdemServico
{
    public class LocalServicoVM
    {
        [JsonProperty(PropertyName = "codigo")]
        public int IDLocal { get; set; }

        [JsonProperty(PropertyName = "nome")]
        public string Nome { get; set; }

        [JsonProperty(PropertyName = "cep")]
        public string CEP { get; set; }

        [JsonProperty(PropertyName = "endereco")]
        public string Endereco { get; set; }

        [JsonProperty(PropertyName = "numero")]
        public string Numero { get; set; }

        [JsonProperty(PropertyName = "complemento")]
        public string Complemento { get; set; }

        [JsonProperty(PropertyName = "bairro")]
        public string Bairro { get; set; }

        [JsonProperty(PropertyName = "cidade")]
        public string Cidade { get; set; }

        [JsonProperty(PropertyName = "uf")]
        public string UF { get; set; }

        [JsonProperty(PropertyName = "nomeContato")]
        public string NomeContato { get; set; }

        [JsonProperty(PropertyName = "telefone")]
        public string Telefone { get; set; }

        [JsonProperty(PropertyName = "whatsApp")]
        public string WhatsApp { get; set; }

        [JsonProperty(PropertyName = "observacao")]
        public string Observacao { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Models/OrdemServico/OrdemServicoItemVM.cs
using Newtonsoft.Json;

namespace Sistema.TSTOnline.Web.Models.OrdemServico
{
    public class OrdemServicoItemVM
    {
        [JsonProperty(PropertyName = "codigo")]
        public int IDOrdemServicoItem { get; set; }

        [JsonProperty(PropertyName = "codigoOrdemServico")]
        public int IDOrdemServico { get; set; }

        [JsonProperty(PropertyName = "item")]
        public int Item { get; set; }

        [JsonProperty(PropertyName = "idTipoServico")]
        public int IDTipoServico { get; set; }

        [JsonProperty(PropertyName = "tipoServicoDescricao")]
        public string TipoServicoDescricao { get; set; }

        [JsonProperty(PropertyName = "observacao")]
        public string Observacao { get; set; }

        [JsonProperty(PropertyName = "concluido")]
        public bool Concluido { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Models/OrdemServico/OrdemServicoVM.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Sistema.TSTOnline.Domain.Utils;

namespace Sistema.TSTOnline.Web.Models.OrdemServico
{
    public class OrdemServicoVM
    {
        [JsonProperty(PropertyName = "idOrdemServico")]
        public int IDOrdemServico { get; set; }

        [JsonProperty(PropertyName = "dataCadastro")]
        public DateTime DataCadastro { get; set; }

        [JsonProperty(PropertyName = "dataServico")]
        public DateTime DataServico { get; set; }

        [JsonProperty(PropertyName = "horarioServico")]
        public string HorarioServico { get; set; }

        [JsonProperty(PropertyName = "status")]
        public OrdemServicoStatusEnum Status { get; set; }

        [JsonProperty(PropertyName = "statusDescricao")]
        public string StatusDescricao { get { return Status.ToDescriptionEnum(); } }

        [JsonProperty(PropertyName = "osExpress")]
        public bool OsExpress { get; set; }

        [JsonProperty(PropertyName = "idEmpresa")]
        public int IDEmpresa { get; set; }

        [JsonProperty(PropertyName = "tipoPessoa")]
        public TipoPessoa TipoPessoa { get; set; }

        [JsonProperty(PropertyName = "cpf")]
        public string CPF { get; set; }

        [JsonProperty(PropertyName = "cnpj")]
        public string CNPJ { get; set; }

        [JsonProperty(PropertyName = "nomeOuRazaoSocial")]
        public string NomeOuRazaoSocial { get; set; }

        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        [JsonProperty(PropertyName = "cep")]
        public string CEP { get; set; }

        [JsonProperty(PropertyName = "endereco")]
        public string Endereco { get; set; }

        [JsonProperty(PropertyName = "numero")]
        public string Numero { get; set; }

        [JsonProperty(PropertyName = "complemento")]
        public string Complemento { get; set; }

        [JsonProperty(PropertyName = "bairro")]
        public string Bairro { get; set; }

        [JsonProperty(PropertyName = "cidade")]
        public string Cidade { get; set; }

        [JsonProperty(PropertyName = "uf")]
        public string UF { get; set; }

        [JsonProperty(PropertyName = "telefoneOE")]
        public string TelefoneOE { get; set; }

        [JsonProperty(PropertyName = "whatsAppOE")]
        public string WhatsAppOE { get; set; }

        [JsonProperty(PropertyName = "razaoSocial")]
        public string RazaoSocial { get; set; }

        [JsonProperty(PropertyName = "idResp")]
        public int IDResp { get; set; }

        [JsonProperty(PropertyName = "responsavelNome")]
        public string ResponsavelNome { get; set; }

        [JsonProperty(PropertyName = "idLocal")]
        public int IDLocal { get; set; }

        [JsonProperty(PropertyName = "localDescricao")]
        public string LocalDescricao { get; set; }

        [JsonProperty(PropertyName = "nomeEstab")]
        public string NomeEstab { get; set; }

        [JsonProperty(PropertyName = "cepEstab")]
        public string CepEstab { get; set; }

        [JsonProperty(PropertyName = "enderecoEstab")]
        public string EnderecoEstab { get; set; }

        [JsonProperty(PropertyName = "numeroEstab")]
        public string NumeroEstab { get; set; }

        [JsonProperty(PropertyName = "complementoEstab")]
        public string ComplementoEstab { get; set; }

        [JsonProperty(PropertyName = "bairroEstab")]
        public string BairroEstab { get; set; }

        [JsonProperty(PropertyName = "cidadeEstab")]
        public string CidadeEstab { get; set; }

        [JsonProperty(PropertyName = "ufEstab")]
        public string UFEstab { get; set; }

        [JsonProperty(PropertyName = "nomeContato")]
        public string NomeContato { get; set; }

        [JsonProperty(PropertyName = "telefone")]
        public string Telefone { get; set; }

        [JsonProperty(PropertyName = "whatsApp")]
        public string WhatsApp { get; set; }

        [JsonProperty(PropertyName = "ordemServicoItens")]
        public List<OrdemServicoItemVM> OrdemServicoItens { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Models/OrdemServico/TipoServicoVM.cs
using Newtonsoft.Json;

namespace Sistema.TSTOnline.Web.Models.OrdemServico
{
    public class TipoServicoVM
    {
        [JsonProperty(PropertyName = "codigo")]
        public int IDTipoServico { get; set; }

        [JsonProperty(PropertyName = "descricao")]
        public string Descricao { get; set; }
    }
}

Site/src/Sistema.TSTOnline.Web/Controllers/OrdemServicoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Sistema.TSTOnline.Domain.Entities.OrdemServico;
using Sistema.TSTOnline.Domain.Interfaces;
using Sistema.TSTOnline.Domain.Services.OrdemServico;
using Sistema.TSTOnline.Web.Models.OrdemServico;
using System.Linq;
using Sistema.TSTOnline.Domain.Utils;
using Sistema.TSTOnline.Domain.Entities.Cadastros;
using System.Collections.Generic;
using System;
using Sistema.TSTOnline.Domain.Services.Template;
using Sistema.TSTOnline.Domain.Services.Usuario;
using Microsoft.Extensions.Configuration;
using Sistema.TSTOnline.Domain.Services.Cadastros;

namespace Sistema.TSTOnline.Web.Controllers
{
    [Route("[controller]")]
    [AllowAnonymous]
    public class OrdemServicoController : Controller
    {
        #region Variables

        private readonly IRepository<LocalServicoEN> _localServicoRepository;
        private readonly LocalServicoBU _localServicoBU;

        private readonly IRepository<TipoServicoEN> _tipoServicoRepository;
        private readonly TipoServicoBU _tipoServicoBU;

        private readonly IRepository<OrdemServicoEN> _ordemServicoRepository;
        private readonly OrdemServicoBU _ordemServicoBU;

        private readonly IRepository<OrdemServicoItemEN> _ordemServicoItemRepository;
        private readonly OrdemServicoItemBU _ordemServicoItemBU;

        private readonly IRepository<ResponsavelEN> _responsavelRepository;

        private readonly IRepository<EmpresaEN> _empresaRepository;
        private readonly EmpresaBU _empresaBU;

        private readonly IRepository<AmbienteEN> _ambienteRepository;
        private readonly AmbienteBU _ambienteBU;

        private readonly IConfiguration _configuration;

        private readonly TemplateBU _templateBU;

        private readonly UsuarioService _usuarioService;

        private int idCompany => _usuarioService.GetCompanyId();

        private int idUser => _usuarioService.GetUserId();

        #endregion Variables

        #region Constructor

        public OrdemServicoController(
                IRepository<LocalServicoEN> localServicoRepository, LocalServicoBU localServicoBU,
                IRepository<TipoServicoEN> tipoServicoRepository, TipoServicoBU tipoServicoBU,
                IRepository<OrdemServicoEN> ordemServicoRepository, OrdemServicoBU ordemServicoBU,
                IRepository<OrdemServicoItemEN> ordemServicoItemRepository, OrdemServicoItemBU ordemServicoItemBU,
                IRepository<ResponsavelEN> responsavelRepository,
                IRepository<EmpresaEN> empresaRepository, EmpresaBU empresaBU,
                IRepository<AmbienteEN> ambienteRepository, AmbienteBU ambienteBU,
                IConfiguration configuration,
                TemplateBU templateBU,
                UsuarioService usuarioService
            )
        {
            _localServicoRepository = localServicoRepository;
            _localServicoBU = localServicoBU;

            _tipoServicoRepository = tipoServicoRepository;
            _tipoServicoBU = tipoServicoBU;

            _ordemServicoRepository = ordemServicoRepository;
            _ordemServicoBU = ordemServicoBU;

            _ordemServicoItemRepository = ordemServicoItemRepository;
            _ordemServicoItemBU = ordemServicoItemBU;

            _responsavelRepository = responsavelRepository;

            _empresaRepository = empresaRepository;
            _empresaBU = empresaBU;

            _ambienteRepository = ambienteRepository;
            _ambienteBU = ambienteBU;

            _configuration = configuration;

            _templateBU = templateBU;

            _usuarioService = usuarioService;
        }

        #endregion Constructor

        #region Locais de Serviço

        [HttpGet]
        [Route("localServico")]
        public IActionResult LocalServico(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("localServicoAddEdit/{idLocalServico?}")]
        public IActionResult LocalServicoAddEdit(int? idLocalServico)
        {
            if (idLocalServico != null)
            {
                var localServico = _localServicoRepository.GetByID(idLocalServico ?? 0);

                var localServicoVM = new LocalServicoVM()
                {
                    IDLocal = localServico.IDLocal,
                    Nome = localServico.Nome,
                    CEP = localServico.CEP,
                    Endereco = localServico.Endereco,
                    Numero = localServico.Numero,
                    Complemento = localServico.Complemento,
                    Bairro = localServico.Bairro,
                    Cidade = localServico.Cidade,
                    UF = localServico.UF,
                    NomeContato = localServico.NomeContato,
                    Telefone = localServico.Telefone,
                    WhatsApp = localServico.WhatsApp,
                    Observacao = localServico.Observacao
                };

                return View(localServicoVM);
            }

            return View();
        }

        [HttpGet]
        [Route("listLocaisServicos")]
        public JsonResult ListLocaisServicos()
        {
            var listLocalServico = _localServicoRepository.Where(obj => obj.IDCompany == idCompany).ToList();
            var localServicoVM = listLocalServico.Select(
                c => new LocalServicoVM
                {
                    IDLocal = c.IDLocal,
                    Nome = c.Nome,
                    CEP = c.CEP,
                    Endereco = c.Endereco,
                    Numero = c.Numero,
                    Complemento = c.Complemento,
                    Bairro = c.Bairro,
                    Cidade = c.Cidade,
                    UF = c.UF,
                    NomeContato = c.NomeContato,
                    Telefone = c.Telefone,
                    WhatsApp = c.WhatsApp
                });

            return Json(localServicoVM.ToList());
        }

        [HttpPost]
        [Route("localServicoCreateOrUpdate")]
        public IActionResult LocalServicoCreateOrUpdate(LocalServicoVM localServicoVM)
        {
            _localServicoBU.Save
                (
                    localServicoVM.IDLocal,
                    idCompany,
                    idUser,
                    localServicoVM.Nome,
                    localServicoVM.CEP,
                    localServicoVM.Endereco,
                    localServicoVM.Numero,
                    localServicoVM.Complemento,
                    localServicoVM.Bairro,
                    localServicoVM.Cidade,
                    localServicoVM.UF,
                    localServicoVM.NomeContato,
                    localServicoVM.Telefone,
                    localServicoVM.WhatsApp,
                    localServicoVM.Observacao
               );

            return Ok();
        }

        [HttpDelete]
        [Route("localServicoDelete/{id}")]
        public IActionResult LocalServicoDelete(int id)
        {
            _localServicoRepository.Delete(id);

            return Ok();
        }

        #endregion Locais de Serviço

        #region Tipos de Serviços

        [HttpGet]
        [Route("tipoServico")]
        public IActionResult TipoServico(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("tipoServicoAddEdit/{idTipoServico?}")]
        public IActionResult TipoServicoAddEdit(int? idTipoServico)
        {
            if (idTipoServico != null)
            {
                var tipoServico = _tipoServicoRepository.GetByID(idTipoServico ?? 0);

                var tipoServicoVM = new TipoServicoVM()
                {
                    IDTipoServico = tipoServico.IDTipoServico,
                    Descricao = tipoServico.Descricao
                };

                return View(tipoServicoVM);
            }

            return View();
        }

        [HttpGet]
        [Route("listTiposServicos")]
        public JsonResult ListTipoServicos()
        {
            var listTipoServico = _tipoServicoRepository.Where(obj => obj.IDCompany == idCompany).ToList();
            var tipoServicoVM = listTipoServico.Select(
                c => new TipoServicoVM
                {
                    IDTipoServico = c.IDTipoServico,
                    Descricao = c.Descricao
                });

            return Json(tipoServicoVM.ToList());
        }

        [HttpPost]
        [Route("tipoServicoCreateOrUpdate")]
        public IActionResult TipoServicoCreateOrUpdate(TipoServicoVM tipoServicoVM)
        {
            _tipoServicoBU.Save
                (
                    tipoServicoVM.IDTipoServico,
                    idCompany,
                    idUser,
                    tipoServicoVM.Descricao
               );

            return Ok();
        }

        [HttpDelete]
        [Route("tipoServicoDelete/{id}")]
        public IActionResult TipoServicoDelete(int id)
        {
            _tipoServicoRepository.Delete(id);

            return Ok();
        }

        #endregion Tipos de Serviços

        #region Ordem de Serviço

        [HttpGet]
        [Route("ordemServico")]
        public IActionResult OrdemServico(int? idCompany, int? idUser)
        {
            _usuarioService.SetUserId(idCompany ?? 0, idUser ?? 0);
            return View();
        }

        [HttpGet]
        [Route("ordemServicoAddEdit/{idServico?}")]
        public IActionResult OrdemServicoAddEdit(int? idServico)
        {
            if (idServico != null)
            {
                var ordemServico = _ordemServicoRepository.GetByID(idServico ?? 0);

                var ordemServicoVM = new OrdemServicoVM()
                {
                    IDOrdemServico = ordemServico.IDOrdemServico,

Site/src/Sistema.TSTOnline.Web/Views/OrdemServico/LocalServico.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "LOCAIS DE SERVIÇOS";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <a href="/ordemservico/LocalServicoAddEdit" class="btn btn-primary">
            <i class="fa fa-plus fa-lg"></i> Novo Local de Serviço
        </a>
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblLocalServico" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Código</th>
                <th width="30%" data-column-id="nome">Nome</th>
                <th width="15%" data-column-id="cep">CEP</th>
                <th width="15%" data-column-id="bairro">Bairro</th>
                <th width="10%" data-column-id="commands1">Editar</th>
                <th width="10%" data-column-id="commands3">Delete</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

</div>

@await Html.PartialAsync("~/Views/Shared/_ConfirmActionPartial.cshtml", 0)

@section Scripts{
    <script src="~/js/ordemservico/localServico.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/OrdemServico/LocalServicoAddEdit.cshtml
@model Sistema.TSTOnline.Web.Models.OrdemServico.LocalServicoVM
@using Sistema.TSTOnline.Domain.Services.Usuario
@using Sistema.TSTOnline.Domain.Utils

@inject UsuarioService _usuarioService

@{
    int idUser = _usuarioService.GetCompanyId();
    var newRegister = Model == null;
    var labelButton = "Cadastrar Local Serviço";

    if (newRegister)
    {
        ViewData["Title"] = "NOVO LOCAL SERVIÇO";
    }
    else
    {
        ViewData["Title"] = "EDITAR LOCAL SERVIÇO";
        labelButton = "Atualizar Local Serviço";
    }
}

<form id="frmLocalServico" asp-action="LocalServicoCreateOrUpdate" asp-controller="OrdemServico"
      data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location='/ordemservico/localservico'">
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DO LOCAL DO SERVIÇO</span></h5>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-2 col-lg-2">
                        @Html.HiddenFor(m => m.IDLocal, new { id = "idLocalServico" })
                        @Html.TextBoxFor(m => m.IDLocal, new { @class = "form-control", @placeholder = "Código", @disabled = "disabled" })
                    </div>

                    <div class="col-sm-10 col-lg-10">
                        @Html.TextBoxFor(m => m.Nome, new { @class = "form-control", @maxlength = "100", @placeholder = "Nome do Local", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DE ENDEREÇO</span></h5>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-3 col-lg-3">
                        @Html.TextBoxFor(m => m.CEP, new { @class = "form-control", @maxlength = "9", @placeholder = "CEP", @required = "true", @data_mask = "00000-000" })
                    </div>

                    <div class="col-sm-7 col-lg-7">
                        @Html.TextBoxFor(m => m.Endereco, new { @class = "form-control", @maxlength = "200", @placeholder = "Endereço", @required = "true" })
                    </div>

                    <div class="col-sm-2 col-lg-2">
                        @Html.TextBoxFor(m => m.Numero, new { @class = "form-control", @maxlength = "80", @placeholder = "Número" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">

                    <div class="col-sm-4 col-lg-4">
                        @Html.TextBoxFor(m => m.Complemento, new { @class = "form-control", @maxlength = "100", @placeholder = "Complemento" })
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        @Html.TextBoxFor(m => m.Bairro, new { @class = "form-control", @maxlength = "80", @placeholder = "Bairro" })
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        @Html.TextBoxFor(m => m.Cidade, new { @class = "form-control", @maxlength = "50", @placeholder = "Cidade" })
                    </div>

                    <div class="col-sm-2 col-lg-2">
                        <select name="uf" class="form-control" required="">

                            @if (newRegister)
                            {
                                <option selected disabled>UF</option>
                            }

                            @foreach (var itemEstado in Helper.ListarEstados())
                            {
                                @if (newRegister)
                                {
                                    <option select value="@itemEstado.Codigo">@itemEstado.Sigla</option>
                                }
                                else if (Model.UF == itemEstado.Sigla)
                                {
                                    <option selected value="@itemEstado.Codigo">@itemEstado.Sigla</option>
                                }
                                else
                                {
                                    <option value="@itemEstado.Codigo">@itemEstado.Sigla</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DO CONTATO</span></h5>
                    </div>
                </div>

                <div class="row">

                    <div class="col-sm-6 col-lg-6">
                        @Html.TextBoxFor(m => m.NomeContato, new { @class = "form-control", @maxlength = "45", @placeholder = "Nome", @required = "true" })
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        @Html.TextBoxFor(m => m.Telefone, new { @class = "form-control", @maxlength = "15", @placeholder = "Telefone", @required = "true", @data_mask = "(00) 00000-0000" })
                    </div>

                    <div class="col-sm-3 col-lg-3">
                        @Html.TextBoxFor(m => m.WhatsApp, new { @class = "form-control", @maxlength = "15", @placeholder = "WhatsApp", @required = "true", @data_mask = "(00) 00000-0000" })
                    </div>

                </div>

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">OBSERVAÇÕES</span></h5>
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col-sm-12 col-lg-12">
                        @Html.TextAreaFor(m => m.Observacao, new { @class = "form-control", @placeholder = "Observação", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save fa-lg"></i> @labelButton
                            </button>
                            <button type="button" onclick="javascript:window.location='/ordemservico/localservico'" class="btn btn-danger">
                                <i class="fas fa-undo fa-lg"></i> Voltar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Site/src/Sistema.TSTOnline.Web/Views/OrdemServico/OrdemServico.cshtml
@using Sistema.TSTOnline.Domain.Utils;

@{
    ViewData["Title"] = "ORDENS DE SERVIÇO";
}

<div class="row justify-content-center">
    <div class="btn-group">
        <a href="/ordemservico/ordemServicoAddEdit" class="btn btn-primary">
            <i class="fa fa-plus fa-lg"></i> Nova Ordem de Serviço
        </a>
        <button class="btn btn-danger" onClick="backToHome()"><i class="fa fa-undo fa-lg"></i> Voltar</button>
    </div>
</div>

<div class="table-responsive">
    <table id="tblOrdemServico" class="table table-striped table-bordered table-hover">
        <thead class="text-uppercase">
            <tr>
                <th data-column-id="id" data-type="numeric">Código</th>
                <th width="10%" data-column-id="dataCadastro">Data Cadastro</th>
                <th width="10%" data-column-id="dataServico">Data Serviço</th>
                <th width="20%" data-column-id="statusDescricao">Status</th>
                <th width="20%" data-column-id="razaoSocial">Cliente</th>
                <th width="20%" data-column-id="responsavelNome">Responsável</th>
                <th width="20%" data-column-id="localDescricao">Local</th>
                <th width="10%" data-column-id="osExpress">Ex</th>
                <th width="10%" data-column-id="commands1">Editar</th>
                <th width="10%" data-column-id="commands3">Cancelar</th>
                <th width="10%" data-column-id="commands1">Imprimir O.S</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@await Html.PartialAsync("~/Views/Shared/_ConfirmActionPartial.cshtml", 1)

@section Scripts{
    <script src="~/js/ordemservico/ordemServico.js?v=@Helper.GetVersion()"></script>
}

Site/src/Sistema.TSTOnline.Web/Views/OrdemServico/TipoServicoAddEdit.cshtml
@model Sistema.TSTOnline.Web.Models.OrdemServico.TipoServicoVM
@using Sistema.TSTOnline.Domain.Services.Usuario

@inject UsuarioService _usuarioService

@{
    int idCompany = _usuarioService.GetCompanyId();
    var newRegister = Model == null;
    var labelButton = "Cadastrar Tipo Serviço";

    if (newRegister)
    {
        ViewData["Title"] = "NOVO TIPO SERVIÇO";
    }
    else
    {
        ViewData["Title"] = "EDITAR TIPO SERVIÇO";
        labelButton = "Atualizar Tipo Serviço";
    }
}

<form id="frmTipoServico" asp-action="TipoServicoCreateOrUpdate" asp-controller="OrdemServico"
      data-ajax="true" data-ajax-method="POST" data-ajax-failure="formOnFail" data-ajax-success="window.location='/ordemservico/tiposervico'">
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row" style="margin-top:1%;">
                    <div class="col-12">
                        <h5><span class="badge badge-secondary w-100 text-left">DADOS DO TIPO DE SERVIÇO</span></h5>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-2 col-lg-2">
                        @Html.HiddenFor(m => m.IDTipoServico, new { id = "idTipoServico" })
                        @Html.TextBoxFor(m => m.IDTipoServico, new { @class = "form-control", @placeholder = "Código", @disabled = "disabled" })
                    </div>

                    <div class="col-sm-10 col-lg-10">
                        @Html.TextBoxFor(m => m.Descricao, new { @class = "form-control", @maxlength = "200", @placeholder = "Descrição", @required = "true" })
                    </div>
                </div>

                <div class="row" style="margin-top: 1%;">
                    <div class="col">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save fa-lg"></i> @labelButton
                            </button>
                            <button type="button" onclick="javascript:window.location='/ordemservico/tiposervico?idCompany=@idCompany'" class="btn btn-danger">
                                <i class="fas fa-undo fa-lg"></i> Voltar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>